### ISSUE TITLE
Allow admin to set global solved ticket target

### ISSUE THREAD

**Issue by jpalmieri** [jpalmieri/zendesk-progress-bar#14]
From a user:

> We wonder if it is possible to set default target in this app for the agents since we know what is their weekly target and agents can follow up from progress bar if they are close this or not? Currently agents can define their own number.

**Comment by Vitordovalep** [comment]
Hey @jpalmieri 

I'm Vitor, from Resultados Digitais.

Does we have any update about this issue on Zendesk's roadmap?

**Comment by jpalmieri** [comment]
Hi @Vitordovalep,

Sorry for any confusion; this app is not officially supported by Zendesk. It was created by me, and I am not  affiliated with Zendesk in any way (at least, _not right now_), except that I have used their products. Since I don't work for Zendesk, I don't know what is on their development roadmap, other than perhaps what is publicly available.

Additionally, sorry for my delayed response. I've been neglecting this app since I no longer work for a company that uses Zendesk. I should note on the `Readme` that this project is no longer under active development. However, this is an open source project, so if you're still looking for this feature, feel free to submit a pull request with the code changes. Noting this issue on the PR will be helpful.

Thanks,
Joe

**Comment by jpalmieri** [comment]
https://github.com/jpalmieri/zendesk-progress-bar/pull/16
